In [1]:
from models import SentenceEmbedders, utils
from models import experiments

### Tests

In [41]:
bert_tests = utils.load_pkl('bert-embeddings/bert_tests_allLayers_maxlen200.pkl')

In [45]:
mc_experiment = experiments.ExperimentResult()
df_tests = experiments.run_similarity_experiments(mc_experiment,
                                                  bert_tests,
                                                  problem_type='multiple-choice',
                                                  strategy=['concat', 'mean', 'max', 'mean_max'], 
                                                  single_layers=[i for i in range(1, 13)],
                                                  layers=[(1, 12), (1, 6), (7, 12), 
                                                          (1, 3), (4, 6), (7, 9), (10, 12)])

Single layers: 100%|██████████| 12/12 [01:23<00:00,  6.93s/it]
Strategies: 100%|██████████| 4/4 [03:50<00:00, 57.69s/it]

In [47]:
print('index of the best accuracy score: ', df_tests['accuracy'].idxmax())
print('index of the best f1: ', df_tests['f1'].idxmax())

index of the best accuracy score:  34
index of the best f1:  13

In [48]:
df_tests

   embeddings_model    layers       pooling  accuracy     f1
0   bert-as-service         1  single_layer     0.298  0.298
1   bert-as-service         2  single_layer     0.297  0.297
2   bert-as-service         3  single_layer     0.297  0.296
3   bert-as-service         4  single_layer     0.300  0.300
4   bert-as-service         5  single_layer     0.300  0.299
5   bert-as-service         6  single_layer     0.300  0.299
6   bert-as-service         7  single_layer     0.288  0.288
7   bert-as-service         8  single_layer     0.284  0.284
8   bert-as-service         9  single_layer     0.280  0.280
9   bert-as-service        10  single_layer     0.274  0.274
10  bert-as-service        11  single_layer     0.275  0.275
11  bert-as-service        12  single_layer     0.296  0.296
12  bert-as-service   (1, 12)        concat     0.290  0.290
13  bert-as-service    (1, 6)        concat     0.302  0.302
14  bert-as-service   (7, 12)        concat     0.284  0.284
15  bert-as-service    (1, 3)        concat     0.298  0.298
16  bert-as-service    (4, 6)        concat     0.300  0.299
17  bert-as-service    (7, 9)        concat     0.285  0.285
18  bert-as-service  (10, 12)        concat     0.278  0.278
19  bert-as-service   (1, 12)          mean     0.296  0.296
20  bert-as-service    (1, 6)          mean     0.301  0.300
21  bert-as-service   (7, 12)          mean     0.282  0.282
22  bert-as-service    (1, 3)          mean     0.297  0.297
23  bert-as-service    (4, 6)          mean     0.300  0.300
24  bert-as-service    (7, 9)          mean     0.282  0.281
25  bert-as-service  (10, 12)          mean     0.279  0.279
26  bert-as-service   (1, 12)           max     0.297  0.297
27  bert-as-service    (1, 6)           max     0.298  0.298
28  bert-as-service   (7, 12)           max     0.293  0.292
29  bert-as-service    (1, 3)           max     0.300  0.300
30  bert-as-service    (4, 6)           max     0.301  0.301
31  bert-as-service    (7, 9)           max     0.284  0.284
32  bert-as-service  (10, 12)           max     0.294  0.294
33  bert-as-service   (1, 12)      mean_max     0.296  0.295
34  bert-as-service    (1, 6)      mean_max     0.303  0.302
35  bert-as-service   (7, 12)      mean_max     0.287  0.287
36  bert-as-service    (1, 3)      mean_max     0.297  0.297
37  bert-as-service    (4, 6)      mean_max     0.300  0.300
38  bert-as-service    (7, 9)      mean_max     0.283  0.283
39  bert-as-service  (10, 12)      mean_max     0.282  0.282

### News

In [2]:
bert_news_1 = utils.load_pkl('bert-embeddings/bert_news_LAYERS_1-6_maxlen200.pkl')
bert_news_2 = utils.load_pkl('bert-embeddings/bert_news_LAYERS_7-12_maxlen200.pkl')

In [3]:
mc_experiment = experiments.ExperimentResult()
df_news_1 = experiments.run_similarity_experiments(mc_experiment,
                                            bert_news_1,
                                            problem_type='multiple-choice',
                                            strategy=['concat', 'mean', 'max', 'mean_max'], 
                                            single_layers=[i for i in range(1, 7)],
                                            layers=[(1, 2), (3, 4), (5, 6), (1, 3), (4, 6), (1, 6)])

Single layers: 100%|██████████| 6/6 [03:36<00:00, 36.09s/it]
Strategies: 100%|██████████| 4/4 [16:50<00:00, 252.67s/it]

In [11]:
mc_experiment = experiments.ExperimentResult()
df_news_2 = experiments.run_similarity_experiments(mc_experiment,
                                                   bert_news_2,
                                                   problem_type='multiple-choice',
                                                   strategy=['concat', 'mean', 'max', 'mean_max'], 
                                                   single_layers=[i for i in range(1, 7)],
                                                   layers=[(1, 2), (3, 4), (5, 6), (1, 3), (4, 6), (1, 6)])

Single layers: 100%|██████████| 6/6 [03:36<00:00, 36.02s/it]
Strategies: 100%|██████████| 4/4 [16:33<00:00, 248.44s/it]

In [17]:
df_news_2['layers'] = df_news_2['layers'].apply(lambda x: (x[0] + 6, x[1] + 6) if isinstance(x, tuple) else x + 6)

In [38]:
import pandas as pd
df_news = pd.concat([df_news_1[:6], df_news_2[:6], df_news_1[6:], df_news_2[6:]])
df_news.reset_index(inplace=True)

In [46]:
print('index of the best accuracy score: ', df_news['accuracy'].idxmax())
print('index of the best f1: ', df_news['f1'].idxmax())

index of the best accuracy score:  11
index of the best f1:  11

In [40]:
df_news

    index embeddings_model    layers       pooling  accuracy     f1
0       0  bert-as-service         1  single_layer     0.429  0.429
1       1  bert-as-service         2  single_layer     0.436  0.436
2       2  bert-as-service         3  single_layer     0.446  0.446
3       3  bert-as-service         4  single_layer     0.440  0.440
4       4  bert-as-service         5  single_layer     0.465  0.465
5       5  bert-as-service         6  single_layer     0.455  0.455
6       0  bert-as-service         7  single_layer     0.441  0.441
7       1  bert-as-service         8  single_layer     0.458  0.458
8       2  bert-as-service         9  single_layer     0.437  0.437
9       3  bert-as-service        10  single_layer     0.445  0.445
10      4  bert-as-service        11  single_layer     0.484  0.484
11      5  bert-as-service        12  single_layer     0.508  0.508
12      6  bert-as-service    (1, 2)        concat     0.433  0.433
13      7  bert-as-service    (3, 4)        concat     0.444  0.444
14      8  bert-as-service    (5, 6)        concat     0.461  0.461
15      9  bert-as-service    (1, 3)        concat     0.441  0.441
16     10  bert-as-service    (4, 6)        concat     0.459  0.459
17     11  bert-as-service    (1, 6)        concat     0.457  0.457
18     12  bert-as-service    (1, 2)          mean     0.434  0.434
19     13  bert-as-service    (3, 4)          mean     0.445  0.445
20     14  bert-as-service    (5, 6)          mean     0.463  0.463
21     15  bert-as-service    (1, 3)          mean     0.442  0.442
22     16  bert-as-service    (4, 6)          mean     0.459  0.459
23     17  bert-as-service    (1, 6)          mean     0.458  0.458
24     18  bert-as-service    (1, 2)           max     0.433  0.433
25     19  bert-as-service    (3, 4)           max     0.444  0.444
26     20  bert-as-service    (5, 6)           max     0.461  0.461
27     21  bert-as-service    (1, 3)           max     0.442  0.442
28     22  bert-as-service    (4, 6)           max     0.457  0.457
29     23  bert-as-service    (1, 6)           max     0.462  0.462
30     24  bert-as-service    (1, 2)      mean_max     0.434  0.434
31     25  bert-as-service    (3, 4)      mean_max     0.445  0.445
32     26  bert-as-service    (5, 6)      mean_max     0.462  0.462
33     27  bert-as-service    (1, 3)      mean_max     0.443  0.443
34     28  bert-as-service    (4, 6)      mean_max     0.458  0.458
35     29  bert-as-service    (1, 6)      mean_max     0.461  0.461
36      6  bert-as-service    (7, 8)        concat     0.452  0.452
37      7  bert-as-service   (9, 10)        concat     0.444  0.444
38      8  bert-as-service  (11, 12)        concat     0.493  0.492
39      9  bert-as-service    (7, 9)        concat     0.449  0.449
40     10  bert-as-service  (10, 12)        concat     0.480  0.480
41     11  bert-as-service   (7, 12)        concat     0.472  0.472
42     12  bert-as-service    (7, 8)          mean     0.454  0.454
43     13  bert-as-service   (9, 10)          mean     0.449  0.449
44     14  bert-as-service  (11, 12)          mean     0.503  0.503
45     15  bert-as-service    (7, 9)          mean     0.453  0.453
46     16  bert-as-service  (10, 12)          mean     0.490  0.490
47     17  bert-as-service   (7, 12)          mean     0.484  0.484
48     18  bert-as-service    (7, 8)           max     0.454  0.454
49     19  bert-as-service   (9, 10)           max     0.448  0.448
50     20  bert-as-service  (11, 12)           max     0.502  0.502
51     21  bert-as-service    (7, 9)           max     0.453  0.453
52     22  bert-as-service  (10, 12)           max     0.489  0.489
53     23  bert-as-service   (7, 12)           max     0.484  0.484
54     24  bert-as-service    (7, 8)      mean_max     0.453  0.453
55     25  bert-as-service   (9, 10)      mean_max     0.449  0.449
56     26  bert-as-service  (11, 12)      mean_max     0.504  0.504
57     27  bert-as-service    (7, 9)      mean_max     0.453  0.453
58     28  bert-as-service  (10, 12)      mean_max     0.490  0.490
59     29  bert-as-service   (7, 12)      mean_max     0.486  0.486

### Paraphrase

In [49]:
bert_paraphrase = utils.load_pkl('bert-embeddings/bert_paraphrase_allLayers_maxlen200.pkl')

In [51]:
paraphrase_experiment = experiments.ExperimentResult()
df_paraphrase = experiments.run_similarity_experiments(paraphrase_experiment,
                                            bert_paraphrase,
                                            problem_type='paraphrase',
                                            strategy=['concat', 'mean', 'max', 'mean_max'], 
                                            single_layers=[i for i in range(1, 13)],
                                            layers=[(1, 12), (1, 6), (7, 12), (1, 3), (4, 6), (6, 8), (9, 12)])

Single layers: 100%|██████████| 12/12 [00:13<00:00,  1.08s/it]
Strategies: 100%|██████████| 4/4 [00:39<00:00,  9.92s/it]

In [52]:
print('index of the best accuracy score: ', df_paraphrase['accuracy'].idxmax())
print('index of the best f1: ', df_paraphrase['f1'].idxmax())

index of the best accuracy score:  22
index of the best f1:  29

In [53]:
df_paraphrase

   embeddings_model   layers       pooling  accuracy     f1
0   bert-as-service        1  single_layer     0.795  0.853
1   bert-as-service        2  single_layer     0.799  0.856
2   bert-as-service        3  single_layer     0.798  0.854
3   bert-as-service        4  single_layer     0.790  0.853
4   bert-as-service        5  single_layer     0.786  0.851
5   bert-as-service        6  single_layer     0.780  0.846
6   bert-as-service        7  single_layer     0.775  0.846
7   bert-as-service        8  single_layer     0.777  0.843
8   bert-as-service        9  single_layer     0.776  0.845
9   bert-as-service       10  single_layer     0.781  0.848
10  bert-as-service       11  single_layer     0.791  0.850
11  bert-as-service       12  single_layer     0.781  0.850
12  bert-as-service  (1, 12)        concat     0.787  0.847
13  bert-as-service   (1, 6)        concat     0.794  0.855
14  bert-as-service  (7, 12)        concat     0.787  0.851
15  bert-as-service   (1, 3)        concat     0.800  0.856
16  bert-as-service   (4, 6)        concat     0.785  0.850
17  bert-as-service   (6, 8)        concat     0.779  0.847
18  bert-as-service  (9, 12)        concat     0.787  0.851
19  bert-as-service  (1, 12)          mean     0.789  0.853
20  bert-as-service   (1, 6)          mean     0.791  0.854
21  bert-as-service  (7, 12)          mean     0.785  0.849
22  bert-as-service   (1, 3)          mean     0.801  0.855
23  bert-as-service   (4, 6)          mean     0.785  0.850
24  bert-as-service   (6, 8)          mean     0.781  0.848
25  bert-as-service  (9, 12)          mean     0.788  0.853
26  bert-as-service  (1, 12)           max     0.788  0.851
27  bert-as-service   (1, 6)           max     0.793  0.856
28  bert-as-service  (7, 12)           max     0.782  0.850
29  bert-as-service   (1, 3)           max     0.793  0.857
30  bert-as-service   (4, 6)           max     0.784  0.851
31  bert-as-service   (6, 8)           max     0.779  0.848
32  bert-as-service  (9, 12)           max     0.783  0.851
33  bert-as-service  (1, 12)      mean_max     0.791  0.856
34  bert-as-service   (1, 6)      mean_max     0.791  0.855
35  bert-as-service  (7, 12)      mean_max     0.787  0.849
36  bert-as-service   (1, 3)      mean_max     0.795  0.856
37  bert-as-service   (4, 6)      mean_max     0.786  0.851
38  bert-as-service   (6, 8)      mean_max     0.782  0.850
39  bert-as-service  (9, 12)      mean_max     0.789  0.852